apiVersion: batch/v1
kind: Job
metadata:
  name: task
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: sleep
        applicationId: "dag01"
        queue: root.default
        children: ""
        executionTime: 300
      name: task
    spec:
      schedulerName: yunikorn
      restartPolicy: Never
      containers:
        - name: sleep300
          image: "alpine:latest"
          command: ["sleep", "300"]
          resources:
            requests:
              cpu: "100m"
              memory: "2000M"