apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "dag01"
    queue: root.default
    children: ""
    executionTime: "300"
  name: task
spec:
  containers:
  - name: sleep300
    image: "alpine:latest"
    command: ["sleep", "30"]
    resources:
      requests:
        cpu: "100m"
        memory: "2000M"
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"