apiVersion: v1
kind: Pod
metadata:
  name: task1
  namespace: default
spec:
  containers:
  - name: sleep300
    image: "alpine:latest"
    command:  ["sleep", "10"]
    resources:
      requests:
        cpu: "100m"
        memory: "2000M"
  restartPolicy: OnFailure
    