tasks:
- name: task1
  children: 
  - name: task2
  - name: task3
  - name: task4
  data: 500
- name: task2
  children:
  - name: task5
  data: 500
- name: task3
  children:
  - name: task5
  - name: task6
  data: 500
- name: task4
  children:
  - name: task7
  data: 500
- name: task5
  children:
  - name: task8
  data: 500
- name: task6
  children:
  - name: task9
  data: 500
- name: task7
  children:
  - name: task9
  - name: task10
  - name: task11
  data: 500
- name: task8
  children:
  - name: task12
  data: 500
- name: task9
  children:
  - name: task12
  data: 500
- name: task10
  children:
  - name: task12
  - name: task13
  - name: task14
  data: 500
- name: task11
  children:
  - name: task14
  data: 500
- name: task12
  children:
  - name: task15
  data: 500
- name: task13
  children:
  - name: task15
  data: 500
- name: task14
  children:
  - name: task15
  data: 500
- name: task15
  children:
  data: 500







