applicationId: dag01
podcount: 24
dependency:
    - idx: 1-15
      weight: 700
    - idx: 2-15
      weight: 200
    - idx: 4-13
      weight: 1000
    - idx: 5-12
      weight: 100
    - idx: 10-12
      weight: 400
    - idx: 10-14
      weight: 500
    - idx: 0-19
      weight: 900
    - idx: 1-20
      weight: 400
    - idx: 2-17
      weight: 500
    - idx: 5-16
      weight: 100
    - idx: 9-17
      weight: 200
    - idx: 9-19
      weight: 400
    - idx: 10-18
      weight: 500
    - idx: 1-24
      weight: 1000
    - idx: 3-25
      weight: 300
    - idx: 8-22
      weight: 700
    - idx: 9-21
      weight: 1000
    - idx: 10-22
      weight: 800
    - idx: 16-22
      weight: 600
    - idx: 18-22
      weight: 500
    - idx: 18-25
      weight: 500
    - idx: 19-22
      weight: 500
    - idx: 20-24
      weight: 600
    - idx: 0-27
      weight: 200
    - idx: 2-29
      weight: 900
    - idx: 3-26
      weight: 300
    - idx: 6-29
      weight: 200
    - idx: 7-26
      weight: 400
    - idx: 8-28
      weight: 800
    - idx: 12-27
      weight: 700
    - idx: 14-26
      weight: 100
    - idx: 14-27
      weight: 100
    - idx: 16-26
      weight: 100
    - idx: 24-26
      weight: 500
    - idx: 24-27
      weight: 600
    - idx: 24-28
      weight: 900
    - idx: 0-30
      weight: 900
    - idx: 1-32
      weight: 800
    - idx: 1-33
      weight: 400
    - idx: 2-32
      weight: 900
    - idx: 4-33
      weight: 500
    - idx: 7-30
      weight: 500
    - idx: 9-32
      weight: 1000
    - idx: 10-31
      weight: 800
    - idx: 12-33
      weight: 400
    - idx: 19-32
      weight: 300
    - idx: 19-33
      weight: 400
    - idx: 20-32
      weight: 200
    - idx: 21-33
      weight: 1000
    - idx: 26-32
      weight: 900
    - idx: 26-33
      weight: 300
    - idx: 28-30
      weight: 900
    - idx: 1-34
      weight: 700
    - idx: 1-36
      weight: 800
    - idx: 3-34
      weight: 900
    - idx: 3-35
      weight: 900
    - idx: 6-34
      weight: 100
    - idx: 12-34
      weight: 1000
    - idx: 13-34
      weight: 300
    - idx: 13-35
      weight: 500
    - idx: 16-36
      weight: 1000
    - idx: 32-36
      weight: 200
    - idx: 33-36
      weight: 300
